---

- name: install compilation-related packages
  sudo: true
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libffi-dev
    - libreadline-dev
    - libssl-dev
    - zlib1g-dev

- name: install curl package
  sudo: true
  apt:
    name=curl
    state=present

- name: install httplib2 package
  sudo: true
  apt:
    name=python-httplib2
    state=present

- name: install unzip package
  sudo: true
  apt:
    name=unzip
    state=present

- name: install the htop package
  sudo: true
  apt:
    name=htop
    state=present

- name: install vim package
  sudo: true
  apt:
    name=vim
    state=present

- name: install emacs package
  sudo: true
  apt:
    name=emacs
    state=present
